api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']

  formats:
    jsonld:   ['application/ld+json']
    json:     ['application/json']
    html:     ['text/html']
    jsonhal:  ['application/hal+json']

  collection:
    pagination:
      items_per_page: 10
      client_items_per_page: true